name: pilapro
favicon: null
layout_spectrum: 0.8924760250374675
typography_spectrum: 0.3548847008496523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.855189032619819
  lightness: 0.7817540306132287
  saturation: 0.22088532033376396
  rhythmicContrast: 0.19325168966315687
purpose: []
